name: amplify_logging_cloudwatch
description: Implementation of Amplify logger plugin with CloudWatch Logs.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/amplify_logging_cloudwatch
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: "^3.0.0"

dependencies:
  amplify_core: ">=1.3.0 <1.4.0"
  amplify_db_common_dart: ">=0.3.0+1 <0.4.0"
  aws_common: ">=0.6.0 <0.7.0"
  aws_logging_cloudwatch: ^0.1.0
  collection: ^1.15.0
  drift: ">=2.11.0 <2.12.0"
  meta: ^1.7.0

dev_dependencies:
  amplify_lints: ">=3.0.0 <3.1.0"
  build_runner: ^2.4.0
  build_test: ^2.0.0
  build_web_compilers: ^4.0.0
  drift_dev: ^2.2.0+1
  test: ^1.22.1
