name: amplify_lints
description: The lint rules used in developing Amplify Flutter packages and plugins.
version: 3.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_lints
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ^3.3.0

dependencies:
  flutter_lints: ^3.0.0
  lints: ^3.0.0
