name: example_common
description: Common components and utils for example apps.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0-444 <4.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  amplify_lints:
    path: ../amplify_lints
  test: ^1.16.0
