name: amplify_auth_cognito_test
description: Tests for the amplify_auth_cognito_dart package.
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  amplify_auth_cognito_dart: ">=0.6.0 <0.7.0"
  amplify_core: ">=1.0.0-next.5 <1.0.0-next.6"
  amplify_secure_storage_dart: ">=0.1.4+2 <0.2.0"
  aws_common: ">=0.4.0 <0.5.0"
  io: ^1.0.0
  json_rpc_2: ^3.0.0
  shelf: ^1.4.0
  shelf_web_socket: ^1.0.0
  stream_channel: ^2.0.0
  test: ^1.22.0
  web_socket_channel: ^2.3.0
  webdriver: ^3.0.0

dev_dependencies:
  amplify_lints:
    path: ../../amplify_lints
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.2.2
  built_collection: ^5.0.0
  built_value: ">=8.4.0 <8.5.0"
  convert: ^3.0.0
  http: ^0.13.0
  smithy: ">=0.4.0+1 <0.5.0"
  smithy_aws: ">=0.4.0+1 <0.5.0"
  stream_transform: ^2.0.0
  worker_bee: ">=0.1.3+2 <0.2.0"
