name: storage_s3_example
description: Amplify Storage S3 for Dart example.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  amplify_auth_cognito_dart: ">=0.9.0 <0.10.0"
  amplify_core: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_secure_storage_dart: ">=0.3.0 <0.4.0"
  amplify_storage_s3_dart: ">=0.2.0 <0.3.0"
  example_common:
    path: ../../../example_common

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
