name: storage_s3_example
description: Amplify Storage S3 for Dart example.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  amplify_auth_cognito_dart: any
  amplify_core: any
  amplify_secure_storage_dart: any
  amplify_storage_s3_dart: any
  example_common:
    path: ../../../example_common

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
