name: smoke_test
description: Smoke test testbed for the AWS SDK for Dart
publish_to: none

environment: 
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  aws_common:
  aws_signature_v4:
  built_collection: ^5.0.0
  built_value: ">=8.4.0 <8.5.0"
  fixnum: ^1.0.0
  meta: ^1.8.0
  smithy:
  smithy_aws:

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.0.0
  built_value_generator: 8.4.2
  test: ^1.19.0
