name: smoke_test
description: Smoke test testbed for the AWS SDK for Dart
publish_to: none

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  aws_common: ">=0.4.0 <0.5.0"
  aws_signature_v4: ">=0.3.1+2 <0.4.0"
  built_collection: ^5.0.0
  built_value: ">=8.4.0 <8.5.0"
  fixnum: ^1.0.0
  meta: ^1.8.0
  smithy: ">=0.4.0+1 <0.5.0"
  smithy_aws: ">=0.4.0+1 <0.5.0"

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.0.0
  built_value_generator: 8.4.3
  test: ^1.19.0
