name: aws_kinesis_datastreams
description: A Dart-only implementation for streaming data to Amazon Kinesis Data Streams with offline support.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/kinesis/aws_kinesis_datastreams
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ^3.9.0

dependencies:
  amplify_core: ">=2.7.0 <2.8.0"
  amplify_db_common_dart: ">=0.4.13 <0.5.0"
  aws_common: ">=0.7.11 <0.8.0"
  aws_signature_v4: ">=0.6.9 <0.7.0"
  built_collection: ^5.1.1
  built_value: ^8.10.1
  drift: ^2.25.0
  meta: ^1.16.0
  smithy: ">=0.7.9 <0.8.0"
  smithy_aws: ">=0.7.9 <0.8.0"

dev_dependencies:
  amplify_lints: ">=3.1.4 <3.2.0"
  build_runner: ^2.4.15
  built_value_generator: ^8.10.1
  drift_dev: ^2.25.1
  fake_async: ^1.3.0
  mocktail: ^1.0.0
  test: ^1.22.1
