# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: amplify_db_common_dart_example
description: Example app for amplify_db_common_dart.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  amplify_db_common_dart: ">=0.2.0+5 <0.3.0"
  drift: ">=2.9.0 <2.10.0"
  example_common:
    path: ../../../example_common

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  drift_dev: ^2.2.0+1
