# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: amplify_db_common_dart_example
description: Example app for amplify_db_common_dart.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  amplify_db_common_dart: ">=0.2.0+1 <0.3.0"
  drift: ">=2.5.0 <2.6.0"
  example_common:
    path: ../../../example_common

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  build_runner: ^2.2.1
  build_web_compilers: ^3.2.3
  drift_dev: ^2.2.0+1
