name: doc
description: Docs examples for the `amplify_core` package.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_core/doc
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ">=3.10.6"

dependencies:
  amplify_analytics_pinpoint: any
  amplify_api: any
  amplify_auth_cognito: any
  amplify_datastore: any
  amplify_flutter: any
  amplify_storage_s3: any
  flutter:
    sdk: flutter

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.4.0
  code_excerpter:
    git:
      url: https://github.com/dart-lang/site-shared
      path: packages/code_excerpter
  test: ^1.22.1
