name: amplify_db_common_dart
description: Common utilities for working with databases such as sqlite. Used throughout Amplify packages.
version: 0.2.0+3
homepage: https://github.com/aws-amplify/amplify-flutter/tree/next
repository: https://github.com/aws-amplify/amplify-flutter/tree/next/packages/common/amplify_db_common_dart
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  amplify_core: ">=1.0.0-next.6 <1.0.0-next.7"
  async: ^2.10.0
  aws_common: ">=0.4.0+1 <0.5.0"
  drift: ">=2.4.0 <2.6.0"
  meta: ^1.7.0
  path: ^1.8.0
  sqlite3: ^1.8.0

dev_dependencies:
  amplify_lints: ">=2.0.2 <2.1.0"
  build_runner: ^2.2.1
  build_test: ^2.0.0
  build_web_compilers: ^3.2.3
  drift_dev: ^2.0.0
  example_common:
    path: ../../example_common
  test: ^1.16.0
