name: amplify_db_common_dart
description: Common utilities for working with databases such as sqlite. Used throughout Amplify packages.
version: 0.3.0+1
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/common/amplify_db_common_dart
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ^3.0.0

dependencies:
  amplify_core: ">=1.2.0 <1.3.0"
  async: ^2.10.0
  aws_common: ">=0.5.0+2 <0.6.0"
  drift: ">=2.9.0 <2.10.0"
  meta: ^1.7.0
  path: ^1.8.0
  sqlite3: ^2.0.0

dev_dependencies:
  amplify_lints: ">=3.0.0 <3.1.0"
  build_runner: ^2.4.0
  build_test: ^2.0.0
  build_web_compilers: ^4.0.0
  drift_dev: ^2.0.0
  test: ^1.22.1
