name: e2e_test
description: E2E tests for the worker_bee package.
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependency_overrides:
  aws_common:
    path: ../../aws_common
  worker_bee:
    path: ../worker_bee

dev_dependencies:
  amplify_lints:
    path: ../../amplify_lints
  aws_common:
    path: ../../aws_common
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.2.3
  built_collection: ^5.0.0
  built_value: ">=8.4.0 <8.5.0"
  built_value_generator: 8.4.2
  e2e:
    path: ../e2e
  meta: ^1.7.0
  test: ^1.19.0
  worker_bee:
    path: ../worker_bee
  worker_bee_builder:
    path: ../worker_bee_builder
