name: amplify_secure_storage_example
description: Demonstrates how to use the amplify_secure_storage plugin and houses the integration tests

publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  amplify_secure_storage:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  amplify_secure_storage_dart:
    path: ../../amplify_secure_storage_test
  amplify_secure_storage_test:
    path: ../../amplify_secure_storage_test
  aws_common:
    path: ../../../aws_common
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path_provider: ^2.0.0

flutter:
  uses-material-design: true
