name: amplify_auth_cognito_example
description: Demonstrates how to use the amplify_auth_cognito plugin.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  amplify_api: any
  amplify_auth_cognito: any
  amplify_authenticator: any
  amplify_core: any
  amplify_flutter: any
  amplify_native_legacy_wrapper: ^0.1.0
  flutter:
    sdk: flutter
  go_router: ^6.5.7

dev_dependencies:
  amplify_api_dart: any
  amplify_auth_cognito_dart: any
  amplify_auth_cognito_test: any
  amplify_auth_integration_test: any
  amplify_integration_test: any
  amplify_lints:
    path: ../../../amplify_lints
  async: ^2.10.0
  aws_signature_v4: any
  checks: ^0.3.0
  collection: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ">=0.13.0 <2.0.0"
  integration_test:
    sdk: flutter
  io: ^1.0.0
  otp: ^3.1.4
  stack_trace: ^1.10.0
  stream_transform: ^2.1.0
  test: ^1.22.1
  webdriver: ^3.0.0
  webview_flutter: ^4.0.0
  webview_flutter_wkwebview: ^3.1.0

flutter:
  uses-material-design: true
