name: amplify_auth_cognito_example
description: Demonstrates how to use the amplify_auth_cognito plugin.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  amplify_api: ">=1.0.0-next.5 <1.0.0-next.6"
  amplify_auth_cognito: ">=1.0.0-next.5 <1.0.0-next.6"
  amplify_authenticator: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_core: ">=1.0.0-next.5 <1.0.0-next.6"
  amplify_flutter: ">=1.0.0-next.5 <1.0.0-next.6"
  flutter:
    sdk: flutter
  go_router: ^3.0.0

dependency_overrides:
  async: ^2.10.0
  meta: ^1.9.0
  test_api: ^0.4.0

dev_dependencies:
  amplify_auth_cognito_dart: ">=0.6.0 <0.7.0"
  amplify_auth_cognito_test: any
  amplify_lints:
    path: ../../../amplify_lints
  amplify_test:
    path: ../../../amplify_test
  async: ^2.10.0
  aws_signature_v4: ">=0.3.1+2 <0.4.0"
  checks: ^0.2.0
  collection: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  io: ^1.0.0
  test: ^1.22.0
  webdriver: ^3.0.0
  webview_flutter: ^4.0.0
  webview_flutter_wkwebview: ^3.1.0

flutter:
  uses-material-design: true
