name: amplify_auth_cognito_example
description: Demonstrates how to use the amplify_auth_cognito plugin.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0-0 <4.0.0"
  flutter: ">=3.10.0-0"

dependencies:
  amplify_api: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_auth_cognito: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_authenticator: ">=1.0.0-next.5+1 <1.0.0-next.6"
  amplify_core: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_flutter: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_native_legacy_wrapper: ^0.1.0
  flutter:
    sdk: flutter
  go_router: ^3.0.0

dependency_overrides:
  # Remove when `checks` is upgraded
  test_api: ^0.5.0

dev_dependencies:
  amplify_auth_cognito_dart: ">=0.9.0 <0.10.0"
  amplify_auth_cognito_test: any
  amplify_integration_test: any
  amplify_lints:
    path: ../../../amplify_lints
  async: ^2.10.0
  aws_signature_v4: ">=0.3.1+2 <0.4.0"
  checks: ^0.2.0
  collection: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^0.13.5
  integration_test:
    sdk: flutter
  io: ^1.0.0
  stack_trace: ^1.10.0
  test: ^1.22.1
  webdriver: ^3.0.0
  webview_flutter: ^4.0.0
  webview_flutter_wkwebview: ^3.1.0

flutter:
  uses-material-design: true
