name: amplify_auth_cognito_example
description: Demonstrates how to use the amplify_auth_cognito plugin.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  amplify_api: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_auth_cognito: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_authenticator: ">=1.0.0-next.3 <1.0.0-next.4"
  amplify_core: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_flutter: ">=1.0.0-next.4 <1.0.0-next.5"
  flutter:
    sdk: flutter
  go_router: ^3.0.0

dev_dependencies:
  amplify_auth_cognito_dart: ">=0.5.0 <0.6.0"
  amplify_lints:
    path: ../../../amplify_lints
  amplify_test:
    path: ../../../amplify_test
  async: ^2.8.0
  aws_signature_v4: ">=0.3.1+2 <0.4.0"
  collection: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
