name: amplified_todo
publish_to: none

environment:
  sdk: ">=3.0.0-0 <4.0.0"
  flutter: ">=3.10.0-0"

dependencies:
  amplify_analytics_pinpoint: ^1.0.0
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_datastore: ^1.0.0-supports-only-mobile.0
  amplify_flutter: ^1.0.0
  amplify_storage_s3: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  amplify_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
