name: goldens
description: Golden files for smithy-dart
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  aws_common:
    path: ../../aws_common
  smithy:
    path: ../smithy

dependency_overrides: 
  aws_common:
    path: ../../aws_common
  aws_signature_v4:
    path: ../../aws_signature_v4
  smithy:
    path: ../smithy
  smithy_aws:
    path: ../smithy_aws
  smithy_codegen:
    path: ../smithy_codegen

dev_dependencies:
  file: ^6.1.2
  glob: ^2.0.2
  lints: ^2.0.0
  path: any
  pubspec_parse: ^1.2.0
  smithy_codegen:
    path: ../smithy_codegen
  test: ^1.16.0
