name: goldens
description: Golden files for smithy-dart
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  aws_common: ^0.5.0+2
  smithy: ^0.5.0+2

dependency_overrides: 
  aws_common:
    path: ../../aws_common
  aws_signature_v4:
    path: ../../aws_signature_v4
  smithy:
    path: ../smithy
  smithy_aws:
    path: ../smithy_aws
  smithy_codegen:
    path: ../smithy_codegen

dev_dependencies:
  args: ^2.3.1
  file: ^7.0.0
  glob: ^2.0.2
  lints: ^2.0.0
  path: any
  pubspec_parse: ^1.2.0
  smithy_codegen:
    path: ../smithy_codegen
  test: ^1.22.1
