name: amplify_foundation_dart
description: Common types and utilities used across Amplify packages.
version: 1.0.0
homepage: https://docs.amplify.aws/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_foundation_dart
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ^3.9.0

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  amplify_lints: ">=3.1.4 <3.2.0"
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.4
  json_serializable: ^6.11.0
  test: ^1.22.1
