name: amplify_authenticator_test
description: A set of a utilities for testing amplify_authenticator
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  amplify_authenticator: ">=1.0.0-next.3 <1.0.0-next.4"
  amplify_flutter: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_test:
    path: ../../amplify_test
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  amplify_lints:
    path: ../../amplify_lints
