name: smithy_test
description: Test utilities for Smithy packages.
version: 0.1.0
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/smithy/smithy_test
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  async: ^2.10.0
  aws_common: any
  aws_signature_v4: any
  built_value: ^8.6.0
  collection: ^1.15.0
  fixnum: ^1.0.0
  path: ">=1.8.0 <2.0.0"
  smithy: any
  test: ^1.22.1
  tuple: ^2.0.0
  xml: ">=6.3.0 <=6.5.0"

dev_dependencies:
  amplify_lints:
    path: ../../amplify_lints
