name: aws_common
description: Common types and utilities used across AWS and Amplify packages.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  async: ^2.8.2
  collection: ^1.15.0
  http: ^0.13.4
  meta: ^1.7.0
  stream_transform: ^2.0.0
  uuid: ^3.0.6

dev_dependencies:
  amplify_lints: ^1.0.0
  test: ^1.16.0
