name: amplify_api_ios_example
description: Test bed for amplify_api_ios
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/api/amplify_api_ios
publish_to: none

environment:
  sdk: ">=2.19.0-444 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  amplify_api: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_flutter: ">=1.0.0-next.4 <1.0.0-next.5"
  flutter:
    sdk: flutter

dependency_overrides:
  amplify_api_ios:
    path: ../
  amplify_flutter_ios:
    path: ../../../amplify/amplify_flutter_ios

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

