name: amplify_secure_storage_test
description: A common set of integration-style tests for amplify secure storage packages
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  amplify_secure_storage_dart: any
  async: ^2.10.0
  aws_common: any
  file: ">=6.0.0 <8.0.0"
  test: ^1.22.1
  worker_bee: any

dev_dependencies:
  amplify_lints:
    path: ../../amplify_lints
  build_runner: ^2.4.0
  build_test: ^2.0.0
  build_web_compilers: ^4.0.0
