name: amplify_storage_plugin_interface
description: The platform interface for the storage module of Amplify Flutter.
version: 0.5.1
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/storage/amplify_storage_plugin_interface

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  amplify_core: 0.5.1

dev_dependencies:
  amplify_test:
    path: ../../amplify_test
  flutter_test:
    sdk: flutter
