name: aws_logging_cloudwatch
description: Implementation of AWS logger plugin with CloudWatch Logs.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/aws_logging_cloudwatch
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: "^3.0.0"

dependencies:
  amplify_core: ">=1.2.0 <1.3.0"
  aws_common: ^0.5.0+2
  aws_signature_v4: ^0.4.0+2
  built_collection: ^5.1.1
  built_value: ">=8.6.0 <8.7.0"
  fixnum: ^1.1.0
  meta: ^1.9.1
  smithy: ^0.5.0+3
  smithy_aws: ^0.5.0+3

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.4.0
  build_test: ^2.0.0
  build_web_compilers: ^4.0.0
  built_value_generator: 8.6.1
  json_serializable: 6.7.0
  test: ^1.22.1
