name: amplify_flutter_ios
description: The method channel implementation for amplify_flutter on iOS
version: 1.0.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify/amplify_flutter_ios
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=3.0.0-0 <4.0.0"
  flutter: ">=3.10.0-0"

dependencies:
  amplify_core: ">=1.0.0 <1.1.0"
  flutter:
    sdk: flutter

dev_dependencies:
  amplify_lints: ">=2.0.3 <2.1.0"
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: Amplify
