name: e2e_flutter_test
description: Flutter testbed for worker_bee
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  e2e:
    path: ../e2e
  flutter:
    sdk: flutter

dependency_overrides:
  aws_common:
    path: ../../aws_common
  worker_bee:
    path: ../worker_bee

dev_dependencies:
  amplify_lints:
    path: ../../amplify_lints
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
