name: {{name}}
description: A starting point for Amplify Dart packages.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/next/{{path}}
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: '{{{dartSdkConstraint}}}'

dependencies:
  amplify_core: '{{{amplifyCoreConstraint}}}'

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  test: ^1.16.0
