# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: amplify_secure_storage_dart_example
description: Example for amplify_secure_storage_dart
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0-444 <4.0.0"

dependencies:
  amplify_secure_storage_dart:
    path: ../
  example_common:
    path: ../../../example_common

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
