# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: amplify_secure_storage_dart_example
description: Example for amplify_secure_storage_dart
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  amplify_secure_storage_dart: ">=0.3.0 <0.4.0"
  example_common:
    path: ../../../example_common

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
