name: amplify_storage_s3_dart
description: A Dart-only implementation of the Amplify Storage plugin for S3.
version: 0.3.1
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/storage/amplify_storage_s3_dart
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ^3.0.0

dependencies:
  amplify_core: ">=1.2.0 <1.3.0"
  amplify_db_common_dart: ">=0.3.0+1 <0.4.0"
  async: ^2.10.0
  aws_common: ">=0.5.0+2 <0.6.0"
  aws_signature_v4: ">=0.4.0+2 <0.5.0"
  built_collection: ^5.0.0
  built_value: ">=8.6.0 <8.7.0"
  drift: ">=2.9.0 <2.10.0"
  fixnum: ^1.0.0
  json_annotation: ">=4.8.1 <4.9.0"
  meta: ^1.7.0
  path: ^1.8.0
  smithy: ">=0.5.0+2 <0.6.0"
  smithy_aws: ">=0.5.0+2 <0.6.0"

dev_dependencies:
  amplify_lints: ">=3.0.0 <3.1.0"
  build_runner: ^2.4.0
  build_verify: ^3.0.0
  built_value_generator: 8.6.1
  drift_dev: ^2.2.0+1
  json_serializable: 6.7.0
  mocktail: ^0.3.0
  test: ^1.22.1
