name: amplify_storage_s3_dart
description: A Dart-only implementation of the Amplify Storage plugin for S3.
version: 0.1.5
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/next/packages/storage/amplify_storage_s3_dart
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  amplify_core: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_db_common_dart: ">=0.2.0+1 <0.3.0"
  async: ^2.8.0
  aws_common: ">=0.4.0 <0.5.0"
  aws_signature_v4: ">=0.3.1+2 <0.4.0"
  built_collection: ^5.0.0
  built_value: ">=8.4.0 <8.5.0"
  drift: ">=2.3.0 <2.4.0"
  fixnum: ^1.0.0
  meta: ^1.7.0
  path: ^1.8.0
  smithy: ">=0.4.0+1 <0.5.0"
  smithy_aws: ">=0.4.1 <0.5.0"

dev_dependencies:
  amplify_lints:
    path: ../../amplify_lints
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  built_value_generator: 8.4.2
  drift_dev: ^2.2.0+1
  mocktail: ^0.3.0
  test: ^1.16.0
