name: amplify_storage_s3_dart
description: A Dart-only implementation of the Amplify Storage plugin for S3.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/next/packages/auth/amplify_storage_s3_dart
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  amplify_core: ">=1.0.0-next.1 <1.0.0-next.2"
  amplify_db_common_dart: ">=0.1.1 <0.2.0"
  async: ^2.8.2
  aws_common: ">=0.3.1 <0.4.0"
  aws_signature_v4: ^0.2.0
  built_collection: ^5.0.0
  built_value: ">=8.4.0 <8.5.0"
  # Constraint determined by amplify_db_common
  drift: any
  meta: ^1.7.0
  path: any
  smithy: ^0.1.0
  smithy_aws: ^0.1.0

dev_dependencies:
  amplify_lints:
    path: ../../amplify_lints
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  built_value_generator: 8.4.2
  drift_dev: ^2.2.0+1
  fixnum: ^1.0.1
  mocktail: ^0.3.0
  test: ^1.16.0
