name: amplify_flutter_example
description: Demonstrates how to use the Amplify Flutter client libraries.
publish_to: none

environment:
  sdk: ">=2.19.0-444 <4.0.0"

dependencies:
  amplify_analytics_pinpoint: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_api: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_auth_cognito: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_datastore: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_flutter: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_storage_s3: ">=1.0.0-next.4 <1.0.0-next.5"
  flutter:
    sdk: flutter

dependency_overrides:
  amplify_api_android:
    path: ../../../api/amplify_api_android
  amplify_api_ios:
    path: ../../../api/amplify_api_ios
  amplify_auth_cognito_android:
    path: ../../../auth/amplify_auth_cognito_android
  amplify_auth_cognito_ios:
    path: ../../../auth/amplify_auth_cognito_ios
  amplify_core:
    path: ../../../amplify_core
  amplify_flutter:
    path: ../
  amplify_flutter_android:
    path: ../../amplify_flutter_android
  amplify_flutter_ios:
    path: ../../amplify_flutter_ios
  amplify_secure_storage:
    path: ../../../secure_storage/amplify_secure_storage
  amplify_secure_storage_dart:
    path: ../../../secure_storage/amplify_secure_storage_dart
  aws_common:
    path: ../../../aws_common
  aws_signature_v4:
    path: ../../../aws_signature_v4

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
