name: amplify_flutter_example
description: Demonstrates how to use the Amplify Flutter client libraries.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  amplify_analytics_pinpoint:
    path: ../../../analytics/amplify_analytics_pinpoint
  amplify_api:
    path: ../../../api/amplify_api
  amplify_auth_cognito:
    path: ../../../auth/amplify_auth_cognito
  amplify_datastore:
    path: ../../../datastore/amplify_datastore
  amplify_flutter:
    path: ../
  amplify_storage_s3:
    path: ../../../storage/amplify_storage_s3
  flutter:
    sdk: flutter

dependency_overrides:
  amplify_analytics_pinpoint_android:
    path: ../../../analytics/amplify_analytics_pinpoint_android
  amplify_analytics_pinpoint_ios:
    path: ../../../analytics/amplify_analytics_pinpoint_ios
  amplify_api_android:
    path: ../../../api/amplify_api_android
  amplify_api_ios:
    path: ../../../api/amplify_api_ios
  amplify_auth_cognito_android:
    path: ../../../auth/amplify_auth_cognito_android
  amplify_auth_cognito_ios:
    path: ../../../auth/amplify_auth_cognito_ios
  amplify_core:
    path: ../../../amplify_core
  amplify_flutter:
    path: ../
  amplify_flutter_android:
    path: ../../amplify_flutter_android
  amplify_flutter_ios:
    path: ../../amplify_flutter_ios
  amplify_secure_storage:
    path: ../../../secure_storage/amplify_secure_storage
  amplify_secure_storage_dart:
    path: ../../../secure_storage/amplify_secure_storage_dart
  amplify_storage_s3_android:
    path: ../../../storage/amplify_storage_s3_android
  amplify_storage_s3_ios:
    path: ../../../storage/amplify_storage_s3_ios
  aws_common:
    path: ../../../aws_common
  aws_signature_v4:
    path: ../../../aws_signature_v4

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
