name: amplify_flutter_example
description: Demonstrates how to use the Amplify Flutter client libraries.
publish_to: none

environment:
  flutter: ">=3.19.0"
  sdk: ^3.3.0

dependencies:
  amplify_analytics_pinpoint: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_api: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_auth_cognito: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_datastore: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_flutter: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_storage_s3: ">=1.0.0-next.8 <1.0.0-next.9"
  flutter:
    sdk: flutter

dependency_overrides:
  amplify_core:
    path: ../../../amplify_core
  amplify_flutter:
    path: ../
  amplify_secure_storage:
    path: ../../../secure_storage/amplify_secure_storage
  amplify_secure_storage_dart:
    path: ../../../secure_storage/amplify_secure_storage_dart
  aws_common:
    path: ../../../aws_common
  aws_signature_v4:
    path: ../../../aws_signature_v4
  test_api: any

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
