name: amplify_storage_s3_example
description: Demonstrates how to use the amplify_storage_s3 plugin.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  amplify_auth_cognito: any
  amplify_authenticator: any
  amplify_core: any
  amplify_flutter: any
  amplify_secure_storage: any
  amplify_storage_s3: any
  flutter:
    sdk: flutter
  go_router: ^6.5.7

dev_dependencies:
  amplify_integration_test: any
  amplify_lints:
    path: ../../../amplify_lints
  amplify_storage_s3_dart: any
  aws_common: any
  drift: ">=2.9.0 <2.10.0"
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ">=0.13.0 <2.0.0"
  integration_test:
    sdk: flutter
  path: any
  stack_trace: ^1.10.0
  test: ^1.22.1

flutter:
  uses-material-design: true
