name: amplify_api_android_example
description: Test bed for amplify_api_android
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/api/amplify_api_android
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  amplify_api: ">=1.0.0-next.6 <1.0.0-next.7"
  amplify_flutter: ">=1.0.0-next.6 <1.0.0-next.7"
  flutter:
    sdk: flutter

dependency_overrides:
  amplify_api_android:
    path: ../
  amplify_flutter_android:
    path: ../../../amplify/amplify_flutter_android

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
