name: amplify_api_android_example
description: Test bed for amplify_api_android
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/api/amplify_api_android
publish_to: "none"

environment:
  sdk: ">=2.19.0-444 <4.0.0"
  flutter: ">=3.7.0-0"

dependencies:
  amplify_api:
    path: ../../amplify_api
  amplify_flutter:
    path: ../../../amplify/amplify_flutter
  flutter:
    sdk: flutter

dependency_overrides:
  amplify_api_android:
    path: ../
  amplify_flutter_android:
    path: ../../../amplify/amplify_flutter_android

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
