name: actions
description: Dart wrapper for the GitHub Actions Node.js modules.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  aws_common: ^0.6.1
  collection: ^1.18.0
  js: ">=0.6.4 <0.8.0"
  json_annotation: ">=4.8.1 <4.9.0"
  path: ">=1.8.0 <2.0.0"
  process: ^5.0.0
  retry: ^3.1.2
  source_map_stack_trace: ^2.1.1
  source_maps: ^0.10.12
  stack_trace: ^1.10.0
  stream_transform: ^2.1.0

dev_dependencies:
  amplify_lints: ^3.0.0
  build_runner: ^2.4.0
  build_test: ^2.2.0
  checks: ^0.3.0
  json_serializable: 6.7.1
  # TODO(equartey): Can be bumped when test_api is bumped to ^0.7.2 in integration_test
  test: ">=1.25.0 <=1.26.0"

aft:
  scripts:
    test:
      from: current
      run: dart --enable-experiment=inline-class test -p node
