name: amplify_push_notifications_pinpoint
description: The Amplify Flutter Push Notifications category plugin using the AWS Pinpoint provider.
version: 1.2.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

# Helps `pana` since it does not detect Android support.
platforms:
  ios:
  android:

dependencies:
  amplify_analytics_pinpoint: ">=1.2.0 <1.3.0"
  amplify_analytics_pinpoint_dart: ">=0.3.0+1 <0.4.0"
  amplify_auth_cognito: ">=1.2.0 <1.3.0"
  amplify_core: ">=1.2.0 <1.3.0"
  amplify_flutter: ">=1.2.0 <1.3.0"
  amplify_push_notifications: ">=1.2.0 <1.3.0"
  amplify_secure_storage: ">=0.4.0+1 <0.5.0"
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.9

dev_dependencies:
  amplify_lints: ">=3.0.0 <3.1.0"
  amplify_secure_storage_dart: ">=0.4.0+2 <0.5.0"
  amplify_test:
    path: ../../../test/amplify_test
  aws_common: ">=0.5.0+2 <0.6.0"
  aws_signature_v4: ">=0.4.0+2 <0.5.0"
  build_runner: ^2.4.0
  built_value_generator: 8.6.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
