name: amplify_push_notifications_pinpoint
description: The Amplify Flutter Push Notifications category plugin using the AWS Pinpoint provider.
version: 2.3.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

# Helps `pana` since it does not detect Android support.
platforms:
  ios:
  android:

dependencies:
  amplify_analytics_pinpoint: ">=2.3.0 <2.4.0"
  amplify_analytics_pinpoint_dart: ">=0.4.3 <0.5.0"
  amplify_auth_cognito: ">=2.3.0 <2.4.0"
  amplify_core: ">=2.3.0 <2.4.0"
  amplify_flutter: ">=2.3.0 <2.4.0"
  amplify_push_notifications: ">=2.3.0 <2.4.0"
  amplify_secure_storage: ">=0.5.4 <0.6.0"
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.9

dev_dependencies:
  amplify_lints: ">=3.1.0 <3.2.0"
  amplify_secure_storage_dart: ">=0.5.1 <0.6.0"
  amplify_test:
    path: ../../../test/amplify_test
  aws_common: ">=0.7.1 <0.8.0"
  aws_signature_v4: ">=0.6.1 <0.7.0"
  build_runner: ^2.4.0
  built_value_generator: 8.8.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
