name: amplify_push_notifications_pinpoint
description: Push Notifications Pinpoint Flutter plugin
version: 1.0.0-next.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  amplify_analytics_pinpoint: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_analytics_pinpoint_dart: ">=0.2.0+1 <0.3.0"
  amplify_auth_cognito: ">=1.0.0-next.8 <1.0.0-next.9"
  amplify_core: ">=1.0.0-next.8+1 <1.0.0-next.9"
  amplify_flutter: ">=1.0.0-next.8+1 <1.0.0-next.9"
  amplify_push_notifications: ">=1.0.0-next.0 <1.0.0-next.1"
  amplify_secure_storage: ">=0.3.0+1 <0.4.0"
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.9

dev_dependencies:
  amplify_lints: ^2.0.0
  amplify_test: any
  build_runner: ^2.0.0
  built_value_generator: 8.4.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
