name: amplify_analytics_plugin_interface
description: The platform interface for the analytics module of Amplify Flutter.
version: 0.5.0
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/analytics/amplify_analytics_plugin_interface

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  amplify_core: 0.5.0
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  amplify_lints: ^1.0.0
  amplify_test:
    path: ../../amplify_test
  flutter_test:
    sdk: flutter
