name: cognito_example
description: Amplify Auth Cognito for Dart example
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  amplify_auth_cognito_dart: any
  amplify_core: any
  amplify_secure_storage_dart: any
  ansicolor: ^2.0.1
  args: ^2.4.1
  example_common:
    path: ../../../example_common
  qr: ^3.0.1

dev_dependencies:
  amplify_api_dart: any
  amplify_auth_cognito_test: any
  amplify_integration_test: any
  amplify_lints:
    path: ../../../amplify_lints
  browser_launcher: ^1.1.1
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  checks: ^0.3.0
  cli_script: ^0.3.0
  io: ^1.0.0
  mime: ^1.0.0
  path: ">=1.8.0 <2.0.0"
  shelf: ^1.4.0
  test: ^1.22.1
  webdriver: ^3.0.0
