name: worker_bee_builder
description: Builder package for worker_bee to quickly generate necessary boilerplate
version: 0.1.4+5
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/worker_bee/worker_bee_builder
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies:
  analyzer: ^5.1.0
  async: ^2.10.0
  build: ^2.2.1
  code_builder: 4.4.0
  collection: ^1.15.0
  dart_style: 2.3.0
  meta: ^1.7.0
  path: ^1.8.0
  source_gen: ^1.2.1
  stream_channel: ^2.1.0
  tuple: ^2.0.0
  worker_bee: ">=0.1.3+6 <0.2.0"

dev_dependencies:
  amplify_lints: ">=2.0.3 <2.1.0"
  test: ^1.22.1
