name: amplify_storage_s3
on:
  push:
    branches:
      - main
      - stable
  pull_request:
    paths:
      - 'packages/storage/amplify_storage_s3/**/*.dart'
      - 'packages/storage/amplify_storage_s3/**/*.yaml'
      - 'packages/storage/amplify_storage_s3/lib/**/*'
      - 'packages/storage/amplify_storage_s3/test/**/*'
      - '.github/workflows/flutter_vm.yaml'
      - '.github/workflows/amplify_storage_s3.yaml'
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00
defaults:
  run:
    shell: bash
permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/flutter_vm.yaml
    with:
      working-directory: packages/storage/amplify_storage_s3
