name: amplify_auth_cognito
on:
  push:
    branches:
      - main
      - stable
  pull_request:
    paths:
      - 'packages/auth/amplify_auth_cognito/**/*.dart'
      - 'packages/auth/amplify_auth_cognito/**/*.yaml'
      - 'packages/auth/amplify_auth_cognito/lib/**/*'
      - 'packages/auth/amplify_auth_cognito/test/**/*'
      - '.github/workflows/flutter_vm.yaml'
      - '.github/workflows/amplify_auth_cognito.yaml'
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00
defaults:
  run:
    shell: bash
permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/flutter_vm.yaml
    with:
      working-directory: packages/auth/amplify_auth_cognito
