name: amplify_auth_cognito iOS
on:
  push:
    branches:
      - main
      - stable
  pull_request:
    paths:
      - 'packages/auth/amplify_auth_cognito/**/*.yaml'
      - 'packages/auth/amplify_auth_cognito/ios/**/*'
      - 'packages/auth/amplify_auth_cognito/example/ios/unit_tests/**/*'
      - 'packages/auth/amplify_auth_cognito_ios/**/*'
      - '.github/workflows/flutter_ios.yaml'
      - '.github/workflows/amplify_auth_cognito.ios.yaml'
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00
defaults:
  run:
    shell: bash
permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/flutter_ios.yaml
    with:
      working-directory: packages/auth/amplify_auth_cognito_ios/example/ios
