# Created with package:mono_repo v6.3.0
name: Build
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: "build_test; PKGS: packages/auth/amplify_auth_cognito_dart, packages/storage/amplify_storage_s3_dart, packages/worker_bee/e2e; `dart test --tags=build`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/auth/amplify_auth_cognito_dart-packages/storage/amplify_storage_s3_dart-packages/worker_bee/e2e;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/auth/amplify_auth_cognito_dart-packages/storage/amplify_storage_s3_dart-packages/worker_bee/e2e
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: packages_auth_amplify_auth_cognito_dart_pub_upgrade
        name: packages/auth/amplify_auth_cognito_dart; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/auth/amplify_auth_cognito_dart
        run: dart pub upgrade
      - name: "packages/auth/amplify_auth_cognito_dart; dart test --tags=build"
        if: "always() && steps.packages_auth_amplify_auth_cognito_dart_pub_upgrade.conclusion == 'success'"
        working-directory: packages/auth/amplify_auth_cognito_dart
        run: "dart test --tags=build"
      - id: packages_storage_amplify_storage_s3_dart_pub_upgrade
        name: packages/storage/amplify_storage_s3_dart; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/storage/amplify_storage_s3_dart
        run: dart pub upgrade
      - name: "packages/storage/amplify_storage_s3_dart; dart test --tags=build"
        if: "always() && steps.packages_storage_amplify_storage_s3_dart_pub_upgrade.conclusion == 'success'"
        working-directory: packages/storage/amplify_storage_s3_dart
        run: "dart test --tags=build"
      - id: packages_worker_bee_e2e_pub_upgrade
        name: packages/worker_bee/e2e; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/worker_bee/e2e
        run: dart pub upgrade
      - name: "packages/worker_bee/e2e; dart test --tags=build"
        if: "always() && steps.packages_worker_bee_e2e_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee/e2e
        run: "dart test --tags=build"
