name: deputy
on:
  pull_request: # TODO: Remove
  schedule:
    - cron: "0 6,12 * * *" # Every day at 06:00 and 12:00
defaults:
  run:
    shell: bash

# These permissions are needed for creating pull requests.
permissions:
  checks: write
  contents: write
  pull-requests: write

# Cancels in-progress job when there is another push to same ref.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # 3.5.3
      - name: Configure Git
        run: |
          git config --global user.email "amplify-flutter@amazon.com"
          git config --global user.name "Amplify Flutter"
      - name: Deputy
        uses: ./.github/composite_actions/deputy_scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
