name: Generate Workflows
on:
  push:
    branches:
      - main
      - stable
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00

jobs:
  test:
    name: Generate Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
        with:
          submodules: true

      - name: Setup Dart
        uses: dart-lang/setup-dart@7f54cd0cee53e120db0d1fce4196b7772ebd6f6e # main
        with:
          sdk: stable

      - name: Setup aft
        shell: bash # Run in bash regardless of platform
        run: dart pub global activate -spath packages/aft

      - name: Generate Workflows
        run: aft generate workflows --set-exit-if-changed
