# ffigen config for glib bindings.
#
# To regenerate, run: `make ffi_bindings_linux`

output: "lib/src/ffi/gio/gio.bindings.g.dart"
name: "Gio"
description: "Bindings to gio"
headers:
  entry-points:
    - "external/glib/gio/gapplication.h"
compiler-opts:
  - "-I./external/glib/"
  - "-I./external/glib/glib/"
functions:
  include:
    - g_application_get_default
    - g_application_get_application_id
structs:
  include:
    - NONE
enums:
  include:
    - NONE
globals:
  include:
    - NONE
macros:
  include:
    - NONE
unions:
  include:
    - NONE
unnamed-enums:
  include:
    - NONE
library-imports:
  glib: "../glib/glib.dart"
type-map:
  "typedefs":
    "GObject":
      "lib": "glib"
      "c-type": "GObject"
      "dart-type": "GObject"
    "gchar":
      "lib": "pkg_ffi"
      "c-type": "Utf8"
      "dart-type": "Char"
comments: false
